title: Streamdata Subscribe - Reddit
url: subscribe.reddit.streamdata.io
tag: Subscribe Reddit
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_org: streamdata-subscribe
github_repo: subscribe-reddit
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
